server:
  port: 8000
  servlet:
    context-path: /ecommerce-nacos-client
spring:
  application:
    name: ecommerce-nacos-client
  cloud:
    nacos: # 服务注册/发现
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
        namespace: c47cfbfd-dc9d-4686-9022-8cb1953b7ad5
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
          user.name: imooc-qinyi
          user.password: 88888888
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
